name: tgstat_posts_handler
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive: ^2.2.3
  http: ^1.1.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  postgres: ^3.5.2

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  very_good_analysis: ^5.1.0
